export const demoProducts = [
  {
    name: "Coffee Beans",
    sku: "COFFEE-001",
    unit: "bag",
    price: 40.0,
    costPrice: 26.0,
    reorderPoint: 30,
    rating: 4.5,
    stockQuantity: 120,
  },
  {
    name: "Milk",
    sku: "MILK-001",
    unit: "liter",
    price: 8.5,
    costPrice: 5.2,
    reorderPoint: 40,
    rating: 3.5,
    stockQuantity: 80,
  },
  {
    name: "Sugar",
    sku: "SUGAR-001",
    unit: "kg",
    price: 6.0,
    costPrice: 3.8,
    reorderPoint: 25,
    rating: 3.0,
    stockQuantity: 18,
  },
  {
    name: "Bread",
    sku: "BREAD-001",
    unit: "loaf",
    price: 12.0,
    costPrice: 7.0,
    reorderPoint: 20,
    rating: 4.0,
    stockQuantity: 12,
  },
  {
    name: "Eggs",
    sku: "EGGS-001",
    unit: "dozen",
    price: 18.0,
    costPrice: 11.5,
    reorderPoint: 24,
    rating: 4.5,
    stockQuantity: 50,
  },
  {
    name: "Rice",
    sku: "RICE-001",
    unit: "kg",
    price: 9.5,
    costPrice: 6.2,
    reorderPoint: 35,
    rating: 4.0,
    stockQuantity: 100,
  },
  {
    name: "Pasta",
    sku: "PASTA-001",
    unit: "pack",
    price: 7.5,
    costPrice: 4.6,
    reorderPoint: 25,
    rating: 3.5,
    stockQuantity: 21,
  },
  {
    name: "Olive Oil",
    sku: "OIL-001",
    unit: "bottle",
    price: 32.0,
    costPrice: 21.0,
    reorderPoint: 18,
    rating: 5.0,
    stockQuantity: 9,
  },
  {
    name: "Butter",
    sku: "BUTTER-001",
    unit: "pack",
    price: 14.0,
    costPrice: 8.8,
    reorderPoint: 20,
    rating: 4.0,
    stockQuantity: 55,
  },
  {
    name: "Cheddar Cheese",
    sku: "CHEESE-001",
    unit: "block",
    price: 22.0,
    costPrice: 14.5,
    reorderPoint: 15,
    rating: 4.5,
    stockQuantity: 8,
  },
  {
    name: "Black Tea",
    sku: "TEA-001",
    unit: "box",
    price: 16.0,
    costPrice: 9.5,
    reorderPoint: 20,
    rating: 3.5,
    stockQuantity: 65,
  },
  {
    name: "Orange Juice",
    sku: "JUICE-001",
    unit: "liter",
    price: 11.0,
    costPrice: 6.8,
    reorderPoint: 22,
    rating: 3.0,
    stockQuantity: 17,
  },
  {
    name: "Breakfast Cereal",
    sku: "CEREAL-001",
    unit: "box",
    price: 18.0,
    costPrice: 11.2,
    reorderPoint: 18,
    rating: 4.0,
    stockQuantity: 11,
  },
  {
    name: "Chocolate Cookies",
    sku: "COOKIES-001",
    unit: "pack",
    price: 10.0,
    costPrice: 5.9,
    reorderPoint: 20,
    rating: 2.5,
    stockQuantity: 75,
  },
  {
    name: "Potato Chips",
    sku: "CHIPS-001",
    unit: "bag",
    price: 9.0,
    costPrice: 5.0,
    reorderPoint: 25,
    rating: 3.5,
    stockQuantity: 90,
  },
  {
    name: "Laundry Detergent",
    sku: "DETERGENT-001",
    unit: "bottle",
    price: 28.0,
    costPrice: 18.0,
    reorderPoint: 12,
    rating: 4.5,
    stockQuantity: 6,
  },
  {
    name: "Dish Soap",
    sku: "DISH-001",
    unit: "bottle",
    price: 9.5,
    costPrice: 5.6,
    reorderPoint: 18,
    rating: 3.0,
    stockQuantity: 60,
  },
  {
    name: "Toilet Paper",
    sku: "TP-001",
    unit: "pack",
    price: 24.0,
    costPrice: 15.0,
    reorderPoint: 16,
    rating: 4.0,
    stockQuantity: 10,
  },
  {
    name: "Hand Soap",
    sku: "SOAP-001",
    unit: "bottle",
    price: 7.0,
    costPrice: 3.9,
    reorderPoint: 20,
    rating: 2.0,
    stockQuantity: 55,
  },
  {
    name: "Shampoo",
    sku: "SHAMPOO-001",
    unit: "bottle",
    price: 19.0,
    costPrice: 12.0,
    reorderPoint: 14,
    rating: 4.0,
    stockQuantity: 9,
  },
] as const;
