export const demoProducts = [
  {
    name: "Coffee Beans",
    sku: "COFFEE-001",
    unit: "bag",
    price: 40.0,
    rating: 4.5,
    stockQuantity: 120,
  },
  {
    name: "Milk",
    sku: "MILK-001",
    unit: "liter",
    price: 8.5,
    rating: 3.5,
    stockQuantity: 80,
  },
  {
    name: "Sugar",
    sku: "SUGAR-001",
    unit: "kg",
    price: 6.0,
    rating: 3.0,
    stockQuantity: 60,
  },
  {
    name: "Bread",
    sku: "BREAD-001",
    unit: "loaf",
    price: 12.0,
    rating: 4.0,
    stockQuantity: 45,
  },
  {
    name: "Eggs",
    sku: "EGGS-001",
    unit: "dozen",
    price: 18.0,
    rating: 4.5,
    stockQuantity: 50,
  },
  {
    name: "Rice",
    sku: "RICE-001",
    unit: "kg",
    price: 9.5,
    rating: 4.0,
    stockQuantity: 100,
  },
  {
    name: "Pasta",
    sku: "PASTA-001",
    unit: "pack",
    price: 7.5,
    rating: 3.5,
    stockQuantity: 70,
  },
  {
    name: "Olive Oil",
    sku: "OIL-001",
    unit: "bottle",
    price: 32.0,
    rating: 5.0,
    stockQuantity: 40,
  },
  {
    name: "Butter",
    sku: "BUTTER-001",
    unit: "pack",
    price: 14.0,
    rating: 4.0,
    stockQuantity: 55,
  },
  {
    name: "Cheddar Cheese",
    sku: "CHEESE-001",
    unit: "block",
    price: 22.0,
    rating: 4.5,
    stockQuantity: 35,
  },
  {
    name: "Black Tea",
    sku: "TEA-001",
    unit: "box",
    price: 16.0,
    rating: 3.5,
    stockQuantity: 65,
  },
  {
    name: "Orange Juice",
    sku: "JUICE-001",
    unit: "liter",
    price: 11.0,
    rating: 3.0,
    stockQuantity: 50,
  },
  {
    name: "Breakfast Cereal",
    sku: "CEREAL-001",
    unit: "box",
    price: 18.0,
    rating: 4.0,
    stockQuantity: 42,
  },
  {
    name: "Chocolate Cookies",
    sku: "COOKIES-001",
    unit: "pack",
    price: 10.0,
    rating: 2.5,
    stockQuantity: 75,
  },
  {
    name: "Potato Chips",
    sku: "CHIPS-001",
    unit: "bag",
    price: 9.0,
    rating: 3.5,
    stockQuantity: 90,
  },
  {
    name: "Laundry Detergent",
    sku: "DETERGENT-001",
    unit: "bottle",
    price: 28.0,
    rating: 4.5,
    stockQuantity: 30,
  },
  {
    name: "Dish Soap",
    sku: "DISH-001",
    unit: "bottle",
    price: 9.5,
    rating: 3.0,
    stockQuantity: 60,
  },
  {
    name: "Toilet Paper",
    sku: "TP-001",
    unit: "pack",
    price: 24.0,
    rating: 4.0,
    stockQuantity: 40,
  },
  {
    name: "Hand Soap",
    sku: "SOAP-001",
    unit: "bottle",
    price: 7.0,
    rating: 2.0,
    stockQuantity: 55,
  },
  {
    name: "Shampoo",
    sku: "SHAMPOO-001",
    unit: "bottle",
    price: 19.0,
    rating: 4.0,
    stockQuantity: 45,
  },
] as const;
